/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/public/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVideoDetailByPath"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMenu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/menu/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["resolveMenuPath"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PublicVideoDetailResponse: {
            title: string;
            sourceTitle: string;
            playlistId: string;
            slug: string;
            fullPath: string;
            description?: string | null;
            thumbnailUrl?: string | null;
            /** Format: int32 */
            itemCount: number;
            /** @enum {string} */
            contentForm: "LONGFORM" | "SHORTFORM";
            groupLabel?: string | null;
            siblings: components["schemas"]["PublicVideoSiblingDto"][];
        };
        PublicVideoSiblingDto: {
            label: string;
            href: string;
        };
        NavigationGroupDto: {
            key: string;
            /** @enum {string} */
            type: "STATIC" | "BOARD" | "FOLDER" | "YOUTUBE_PLAYLIST_GROUP" | "YOUTUBE_PLAYLIST" | "EXTERNAL_LINK";
            label: string;
            href: string;
            matchPath?: string | null;
            /** @enum {string} */
            linkType: "INTERNAL" | "EXTERNAL";
            contentSiteKey?: string | null;
            openInNewTab: boolean;
            visible: boolean;
            headerVisible: boolean;
            mobileVisible: boolean;
            lnbVisible: boolean;
            breadcrumbVisible: boolean;
            defaultLandingHref?: string | null;
            items: components["schemas"]["NavigationItemDto"][];
        };
        NavigationItemDto: {
            key: string;
            /** @enum {string} */
            type: "STATIC" | "BOARD" | "FOLDER" | "YOUTUBE_PLAYLIST_GROUP" | "YOUTUBE_PLAYLIST" | "EXTERNAL_LINK";
            label: string;
            href: string;
            matchPath?: string | null;
            /** @enum {string} */
            linkType: "INTERNAL" | "EXTERNAL";
            contentSiteKey?: string | null;
            openInNewTab: boolean;
            visible: boolean;
            headerVisible: boolean;
            mobileVisible: boolean;
            lnbVisible: boolean;
            breadcrumbVisible: boolean;
            defaultLanding: boolean;
        };
        PublicNavigationResponse: {
            groups: components["schemas"]["NavigationGroupDto"][];
        };
        PublicResolvedMenuPageResponse: {
            /** Format: int64 */
            menuId: number;
            /** @enum {string} */
            type: "STATIC" | "BOARD" | "FOLDER" | "YOUTUBE_PLAYLIST_GROUP" | "YOUTUBE_PLAYLIST" | "EXTERNAL_LINK";
            label: string;
            slug: string;
            fullPath: string;
            parentLabel?: string | null;
            staticPageKey?: string | null;
            boardKey?: string | null;
            redirectTo?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVideoDetailByPath: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicVideoDetailResponse"];
                };
            };
        };
    };
    getMenu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicNavigationResponse"];
                };
            };
        };
    };
    resolveMenuPath: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicResolvedMenuPageResponse"];
                };
            };
        };
    };
}
